apiVersion: apps/v1
kind: Deployment
metadata:
  name: profiling-app
  labels:
    app: profiling-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: profiling-app
  template:
    metadata:
      labels:
        app: profiling-app
    spec:
      containers:
        - name: profiling-app
          image: default-route-openshift-image-registry.apps.rm1.0a51.p1.openshiftapps.com/svnsheene-dev/profiling-gue:1.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8001
              protocol: TCP
          env:
            - name: DB_NAME
              value: "bootcamp"
            - name: MONGO_URI
              value: "mongodb://10.131.10.252"