---
- name: Instalasi dan Setup MongoDB
  hosts: all
  tasks:
    - name: Pastikan Podman terinstal
      ansible.builtin.dnf:
        name: podman
        state: present
      become: true

    - name: Cek apakah container MongoDB sudah berjalan
      ansible.builtin.command: podman ps -q -f name=mongo-db
      register: mongo_status
      changed_when: false

    - name: Hapus sisa container lama jika ada error (Opsional/Pembersihan)
      ansible.builtin.command: podman rm -f mongo-db
      when: mongo_status.stdout == ""
      ignore_errors: true

    - name: Jalankan MongoDB menggunakan Podman
      ansible.builtin.command: podman run -d --name mongo-db -p 27017:27017 docker.io/library/mongo:latest
      when: mongo_status.stdout == ""
