---
- name: Ensure required tooling is installed, validated and logged in
  hosts: all
  tasks:
  - name: Hapus sisa container lama yang error
    ansible.builtin.command: podman rm -f mongo-db
    ignore_errors: true

  - name: Jalankan MongoDB (Mencoba versi 7.0)
    ansible.builtin.command: podman run -d --name mongo-db -p 27017:27017 docker.io/library/mongo:7.0
